# https://pages.github.com/

title: phramusca
description: >
  This is my homepage.
show_downloads: false
remote_theme: pages-themes/hacker
plugins:
  - jekyll-remote-theme
github:
  repository_url: https://github.com/phramusca
collections:
  wiki:
    output: true
    permalink: /wiki/:path/

# Exclure des fichiers du build
exclude:
  - README.md
  - PLAN_AMELIORATION.md
  - TEST_LOCAL.md
  - .devcontainer/
  - .vscode/
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock